# Generated by Django 5.2 on 2025-04-28 04:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('employee_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('employee_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract')], max_length=2)),
                ('employee_department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], max_length=3)),
                ('is_getting_sunday', models.BooleanField(default=True)),
                ('is_getting_ot', models.BooleanField(default=False)),
                ('no_of_cl', models.PositiveIntegerField(default=0)),
                ('working_time_in', models.TimeField()),
                ('working_time_out', models.TimeField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('employee_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract')], max_length=2)),
                ('employee_department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], max_length=3)),
                ('is_getting_sunday', models.BooleanField(default=True)),
                ('is_getting_ot', models.BooleanField(default=False)),
                ('no_of_cl', models.PositiveIntegerField(default=0)),
                ('working_time_in', models.TimeField()),
                ('working_time_out', models.TimeField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee',
                'verbose_name_plural': 'historical employees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
