# Generated by Django 5.2 on 2025-04-28 05:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave blank if holiday is for ALL departments', max_length=3, null=True)),
                ('holiday_date', models.DateField(help_text='Date of the holiday')),
                ('holiday_name', models.CharField(help_text='Reason for holiday (e.g., Diwali, Independence Day)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SundayReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave empty if applicable for ALL departments', max_length=3, null=True)),
                ('sunday_date', models.DateField(help_text='Original Sunday date being replaced')),
                ('replacement_date', models.DateField(help_text='New working day instead of Sunday')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_type',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('ROT', 'Rotational Shift')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='shift_type',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('ROT', 'Rotational Shift')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_time', models.TimeField()),
                ('approved_by', models.CharField(max_length=100)),
                ('action_taken', models.CharField(choices=[('FD', 'Full Day'), ('HD', 'Half Day Cut'), ('FD_CUT', 'Full Day Cut')], max_length=7)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalGatePass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('out_time', models.TimeField()),
                ('approved_by', models.CharField(max_length=100)),
                ('action_taken', models.CharField(choices=[('FD', 'Full Day'), ('HD', 'Half Day Cut'), ('FD_CUT', 'Full Day Cut')], max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical gate pass',
                'verbose_name_plural': 'historical gate passs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHoliday',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave blank if holiday is for ALL departments', max_length=3, null=True)),
                ('holiday_date', models.DateField(help_text='Date of the holiday')),
                ('holiday_name', models.CharField(help_text='Reason for holiday (e.g., Diwali, Independence Day)', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical holiday',
                'verbose_name_plural': 'historical holidays',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalManualPunch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('punch_in_time', models.DateTimeField(blank=True, help_text='Manual Clock-in time (leave blank if missing)', null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, help_text='Manual Clock-out time (leave blank if missing)', null=True)),
                ('reason', models.CharField(help_text='Reason for adding manual punch', max_length=255)),
                ('approved_by', models.CharField(help_text='Name of the approver (e.g., supervisor, HR)', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical manual punch',
                'verbose_name_plural': 'historical manual punchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalODSlip',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('od_date', models.DateField()),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('approved_by', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical od slip',
                'verbose_name_plural': 'historical od slips',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('ROT', 'Rotational Shift')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical shift assignment',
                'verbose_name_plural': 'historical shift assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSundayReplacement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave empty if applicable for ALL departments', max_length=3, null=True)),
                ('sunday_date', models.DateField(help_text='Original Sunday date being replaced')),
                ('replacement_date', models.DateField(help_text='New working day instead of Sunday')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sunday replacement',
                'verbose_name_plural': 'historical sunday replacements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ManualPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in_time', models.DateTimeField(blank=True, help_text='Manual Clock-in time (leave blank if missing)', null=True)),
                ('punch_out_time', models.DateTimeField(blank=True, help_text='Manual Clock-out time (leave blank if missing)', null=True)),
                ('reason', models.CharField(help_text='Reason for adding manual punch', max_length=255)),
                ('approved_by', models.CharField(help_text='Name of the approver (e.g., supervisor, HR)', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_punches', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ODSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_date', models.DateField()),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extra_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('approved_by', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='od_slips', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('ROT', 'Rotational Shift')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='attendance.employee')),
            ],
        ),
    ]
