# Generated by Django 5.2 on 2025-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_holiday_sundayreplacement_employee_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsundayreplacement',
            name='sunday_date',
            field=models.DateField(help_text='Original Sunday date being replaced - attendance is mandatory on this date'),
        ),
        migrations.AlterField(
            model_name='sundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('ACC', 'Accounts'), ('OPS', 'Operations')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sundayreplacement',
            name='sunday_date',
            field=models.DateField(help_text='Original Sunday date being replaced - attendance is mandatory on this date'),
        ),
    ]
