# Generated by Django 5.2 on 2025-04-28 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_historicalsundayreplacement_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.PositiveSmallIntegerField()),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('total_days_in_month', models.PositiveSmallIntegerField()),
                ('total_working_days', models.PositiveSmallIntegerField()),
                ('total_present_days', models.PositiveSmallIntegerField()),
                ('total_absent_days', models.PositiveSmallIntegerField()),
                ('total_leave_days', models.PositiveSmallIntegerField()),
                ('total_holiday_days', models.PositiveSmallIntegerField()),
                ('total_od_days', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_working_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_attendance', models.JSONField()),
                ('od_slips', models.JSONField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_attendances', to='attendance.employee')),
            ],
            options={
                'verbose_name': 'Processed Attendance',
                'verbose_name_plural': 'Processed Attendances',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
