# Generated by Django 5.2 on 2025-04-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_processedattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedattendance',
            old_name='daily_attendance',
            new_name='attendance_data',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='od_slips',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_absent_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_days_in_month',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_holiday_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_leave_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_od_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_overtime_hours',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_present_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_working_days',
        ),
        migrations.RemoveField(
            model_name='processedattendance',
            name='total_working_hours',
        ),
    ]
