# Generated by Django 5.2 on 2025-04-28 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_daily_attendance_processedattendance_attendance_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshiftassignment',
            name='working_time_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalshiftassignment',
            name='working_time_out',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='working_time_in',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='working_time_out',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
