# Generated by Django 5.2 on 2025-04-29 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_historicalshiftassignment_working_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgatepass',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
