# Generated by Django 5.2 on 2025-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_gatepass_date_historicalgatepass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalgatepass',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
