# Generated by Django 5.2 on 2025-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_gatepass_reason_historicalgatepass_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalholiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('CNC', 'CNC'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('CNC', 'CNC'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
    ]
