# Generated by Django 5.2 on 2025-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_employee_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('FORMAN', 'Forman'), ('EXECUTIVESUPERVISOR', 'Executive Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('FORMAN', 'Forman'), ('EXECUTIVESUPERVISOR', 'Executive Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
