# Generated by Django 5.2 on 2025-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_employee_is_active_historicalemployee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('NPD', 'NPD'), ('FORMAN', 'Forman'), ('EXECUTIVE', 'Executive'), ('Supervisor', 'Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head'), ('Designer', 'Designer'), ('Developer', 'Developer'), ('Quality Head', 'Quality Head'), ('SAFETY & SECURITY INCHARGE', 'SAFETY & SECURITY INCHARGE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('NPD', 'NPD'), ('FORMAN', 'Forman'), ('EXECUTIVE', 'Executive'), ('Supervisor', 'Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head'), ('Designer', 'Designer'), ('Developer', 'Developer'), ('Quality Head', 'Quality Head'), ('SAFETY & SECURITY INCHARGE', 'SAFETY & SECURITY INCHARGE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalholiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
    ]
