# Generated by Django 5.2 on 2025-05-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_employee_employee_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='incentive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='incentive',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
