# Generated by Django 5.2 on 2025-05-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employee_incentive_historicalemployee_incentive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('NPD', 'NPD'), ('FORMAN', 'Forman'), ('EXECUTIVE', 'Executive'), ('Supervisor', 'Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head'), ('Designer', 'Designer'), ('Loader', 'Loader'), ('Chaker', 'Chaker'), ('Packer', 'Packer'), ('Visual', 'Visual'), ('Helper', 'Helper'), ('Developer', 'Developer'), ('Quality Head', 'Quality Head'), ('SAFETY & SECURITY INCHARGE', 'SAFETY & SECURITY INCHARGE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='employee_department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position',
            field=models.CharField(choices=[('INCHARGE', 'Incharge'), ('MAINTENANCE', 'Maintenance'), ('QA', 'QA'), ('NPD', 'NPD'), ('FORMAN', 'Forman'), ('EXECUTIVE', 'Executive'), ('Supervisor', 'Supervisor'), ('QUALITY ENGINEER', 'Quality Engineer'), ('OPERATOR', 'Operator'), ('PROGRAMMER', 'Programmer'), ('HEAD', 'Head'), ('Designer', 'Designer'), ('Loader', 'Loader'), ('Chaker', 'Chaker'), ('Packer', 'Packer'), ('Visual', 'Visual'), ('Helper', 'Helper'), ('Developer', 'Developer'), ('Quality Head', 'Quality Head'), ('SAFETY & SECURITY INCHARGE', 'SAFETY & SECURITY INCHARGE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalholiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], help_text='Leave blank if holiday is for ALL departments', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sundayreplacement',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Human Resources'), ('CNC', 'CNC'), ('FORGING', 'FORGING'), ('HAMMER', 'HAMMER'), ('STORE', 'STORE'), ('TOOL ROOM', 'TOOL ROOM'), ('TURNING', 'TURNING'), ('ACCOUNTS', 'ACCOUNTS'), ('RM', 'RM'), ('ENGINEERING', 'ENGINEERING'), ('LAB', 'LAB'), ('FI', 'FI'), ('MAINTENANCE', 'MAINTENANCE'), ('Quality', 'Quality'), ('SECURITY', 'SECURITY'), ('DISPATCH', 'DISPATCH'), ('ELECTRICAL', 'ELECTRICAL'), ('FI-MARKING', 'FI-MARKING'), ('FI-FINAL INSPECTION', 'FI-FINAL INSPECTION'), ('FI-D MAGNET', 'FI-D MAGNET'), ('CANTEEN', 'CANTEEN'), ('HAMMER', 'HAMMER'), ('HEAT TREATMENT', 'HEAT TREATMENT'), ('FI-PACKING & LOADING', 'FI-PACKING & LOADING'), ('FI-VISUAL', 'FI-VISUAL'), ('MATERIAL MOVEMENT', 'MATERIAL MOVEMENT'), ('MPI', 'MPI'), ('RING ROLLING', 'RING ROLLING'), ('SHOT BLAST', 'SHOT BLAST'), ('TURNING', 'TURNING'), ('Other', 'Other')], help_text='Leave empty if applicable for ALL departments. When set, ALL employees in this department MUST work on the replacement date.', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ProcessedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'verbose_name_plural': 'Processed Salaries',
                'indexes': [models.Index(fields=['month', 'year'], name='attendance__month_0f3a3a_idx'), models.Index(fields=['employee'], name='attendance__employe_0c4e8e_idx')],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
