# Generated by Django 5.2 on 2025-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_employee_joining_date_employee_leaving_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_getting_pf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_monthly_salary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_getting_pf',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_monthly_salary',
            field=models.BooleanField(default=True),
        ),
    ]
