# Generated by Django 5.2 on 2025-07-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_notrunningday_historicalnotrunningday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnotrunningday',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Notrunningday',
        ),
        migrations.DeleteModel(
            name='HistoricalNotrunningday',
        ),
    ]
