# Generated by Django 5.2 on 2026-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_gatepass_approved_at_gatepass_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ip_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='ip_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='uan_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
